[project]
name = "e-kyc-using-cn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepface>=0.0.98",
    "matplotlib>=3.10.8",
    "opencv-python>=4.13.0.92",
    "pytesseract>=0.3.13",
    "tf-keras>=2.20.1",
]
